### ISSUE TITLE
Error in select_best_solution(tree, Y, sol, opt = opt)

### ISSUE THREAD

**Issue by kfuku52** [khabbazian/l1ou#26]
Hi, I got a following error when I tried estimate_shift_configuration() on my dataset.

```
Warning message in matrix(ifelse(abs(x[!is.na(grpIdx)]) > 0, 1, 0), ncol = nVariables):
“data length [25] is not a sub-multiple or multiple of the number of columns [6]”Warning message in matrix(ifelse(abs(x[!is.na(grpIdx)]) > 0, 1, 0), ncol = nVariables):
...
Error in select_best_solution(tree, Y, sol, opt = opt): object 'best.shift.configuration' not found
Traceback:

1. estimate_shift_configuration(tree = adj_data$tree, Y = adj_data$Y, 
 .     criterion = "AICc", root.model = "OUrandomRoot", nCores = 1, 
 .     rescale = TRUE)
2. estimate_shift_configuration_known_alpha_multivariate(tree, Y, 
 .     est.alpha = TRUE, opt = l1ou.options)
3. select_best_solution(tree, Y, sol, opt = opt)
```

My session info is:
```
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin11.4.2 (64-bit)
Running under: macOS Sierra 10.12.3

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] l1ou_1.40      genlasso_1.3   Matrix_1.2-7.1 MASS_7.3-45    magic_1.5-6   
 [6] abind_1.4-5    grplasso_0.4-5 lars_1.2       phylolm_2.5    ape_4.0       
[11] igraph_1.0.1  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9     magrittr_1.5    uuid_0.1-2      lattice_0.20-34
 [5] R6_2.2.0        stringr_1.1.0   tools_3.3.2     grid_3.3.2     
 [9] nlme_3.1-128    digest_0.6.10   crayon_1.3.2    IRdisplay_0.4.4
[13] repr_0.10       IRkernel_0.7.1  evaluate_0.10   pbdZMQ_0.2-4   
[17] stringi_1.1.2   jsonlite_1.1   
```

You can reproduce the error using this code.
```
tree_text = '((Canis_lupus_ENSCAFG00000007369:77.75495641,(Bos_taurus_ENSBTAG00000031373:61.96598852,Sus_scrofa_ENSSSCG00000028270:61.96598852)n2:15.78896789)n4:18.70743276,Oryctolagus_cuniculus_ENSOCUG00000010555:96.46238917)n6;'
tree = read.tree(text=tree_text)

trait_text="brain,heart,kidney,liver,ovary,testis
Sus_scrofa_ENSSSCG00000028270,0,0.00613622199739828,0,0,0,0.086648021213729
Bos_taurus_ENSBTAG00000031373,0.0037485584053104,0.0025221135879922,0,0,0,0.0987999096017663
Canis_lupus_ENSCAFG00000007369,0,0.0611830531983022,0.0671139398094019,0.0692757761941058,0,0
Oryctolagus_cuniculus_ENSOCUG00000010555,0,4.48056104371082e-17,0,0,0,1.5554235315619"
trait_matrix = read.table(text=trait_text, sep=",")

adj_data = adjust_data(tree=tree, Y=trait_matrix, normalize = FALSE)
fit_ind = estimate_shift_configuration(tree=adj_data$tree, Y=adj_data$Y, criterion="AICc", root.model="OUrandomRoot", nCores=1, rescale=TRUE)
```

I would appreciate it if you would give me some advice.

Kenji

**Comment by khabbazian** [comment]
Hi Kenji,
 It has something to do with this that your response (trait) matrix has more columns than rows. I will look into it more closely and let you know.

**Comment by kfuku52** [comment]
Thank you for working on this. Is there any update on this issue?

**Comment by khabbazian** [comment]
Sorry I got very busy recently. I will continue working on it this weekend. :)

**Comment by khabbazian** [comment]
Hi, I fixed the error. I was originally wrong. The problem was with the trait matrix. It has a column that is all zero. Anyway, I believe you can run your code without any error now. I will go ahead and close this issue. Thanks again for reporting that. :)

**Comment by kfuku52** [comment]
I re-installed l1ou and tried the above example again. But estimate_shift_configuration() kept silent for 1 hour after showing the message 

"Starting first LASSO (alpha=0) to find a list of candidate configurations." 

and did not finish the calculation. This is strange as the dataset is so small (4 species x 6 traits). I tried this on my macOS and linux but both are the same (still calculating something without error). Did you successfully complete the calculation in reasonable time?

**Comment by khabbazian** [comment]
No it is slow on my computer too. I looked into the code. It is slow because the group lasso (grplasso) has a hard time finding shifts. The algorithm iteratively refines and increases the range of lambda parameters to find different number of shifts. As a result group lasso has to search bigger range of lambdas for your input. I think you should, instead of using all the trait values, pick a few of them.

**Comment by kfuku52** [comment]
OK, I will do so. Thank you for fixing the problem.

**Comment by khabbazian** [comment]
It just occured to me the coefficient corresponding to the trait value that is all zero will be always zero. That is it never happens to be grouped with other traits. That is why grplasso doesn't find a shift that impact all the traits. I successfully ran this code 
fit_ind = estimate_shift_configuration(tree=adj_data$tree, Y=adj_data$Y[,c(1:4,6)], criterion="AICc", root.model="OUrandomRoot", nCores=1)

**Comment by kfuku52** [comment]
Thank you as well for the note!

**Comment by kfuku52** [comment]
I found another problem related to this.
estimate_shift_configuration() finishes within a second by removing the all-zero columns as you suggested like,

`fit_ind = estimate_shift_configuration(tree=adj_data$tree, Y=adj_data$Y[,c(1:4,6)], criterion="AICc", root.model="OUrandomRoot", nCores=1, rescale=TRUE)
`
but following bootstrapping did not finish for long time.

`bootstrap_result = l1ou_bootstrap_support(fit_ind, nItrs=2)`

There are Y columns having multiple zero values and such data have identical residuals. This might be the cause of the problem because the bootstrapping was completed immediately if I add small noise to the residuals before bootstrapping like,

`fit_ind$residuals = jitter(fit_ind$residuals)`

But this is a dirty workaround and I don't want to remove all trait columns having more than one zero values.

I would be grateful if you could find a way to fix the problem.

**Comment by cecileane** [comment]
For small sample sizes (here: 4 taxa), the non-parametric bootstrap is not advisable. Here there are only 4 contrasts to sample from, (3 if we remove the root contrast). When we sample them with replacement to create new data sets, that's only 3<sup>3</sup>=27 combinations of contrasts at 3 internal nodes. So only 27 possible bootstrap data sets. In general, non-parametric bootstrap is known for not being good method for small data sets.

We would need a **parametric bootstrap** implementation instead, for small data sets: to simulate data based on a σ estimate, an α estimate, etc.

On data sets with many taxa, even if a few taxa have the same value (like 0s here), it is quite unlikely that the non-parametric bootstrap will create a trait will the exact same value for all taxa --if there are many taxa, and enough of them don't share the same value. But for data with few taxa: there is both a technical issue (there's a good chance of resampling 0 contrasts at all internal nodes), and there is a methodological issue anyway.

A better fix, here, would be to allow for constant traits with group lasso: make it okay for one trait to *not* jump at the same time as all others. Is there anyway to let `grplasso` do that Mohammad?

**Comment by kfuku52** [comment]
Thank you. I will limit the use of nonparametric bootstrapping to larger datasets.
