### ISSUE TITLE
estimate_convergent_regimes error

### ISSUE THREAD

**Issue by grahamjslater** [khabbazian/l1ou#32]
the function estimate_convergent_regimes appears to be broken - running it returns the following error:
Error in sqrt_OU_covariance(tr, alpha = alpha, root.model = "OUfixedRoot",  : 
  unused argument (normalize.tree.height = TRUE)

It can be traced to the function find_convergent_regimes, which calls sqrt_OU_covariance but with the argument normalize.tree.height=TRUE, which is missing from that function's definition.

**Comment by khabbazian** [comment]
I don't get the error. But anyway, I guessed what might cause that error. I think I've fixed it. Could you run it again?

**Comment by grahamjslater** [comment]
You didn't get it? Weird. I tried installing on a couple different machines with different OS's and got it both times, but editing the source code and rebuilding the package fixed it.

Anyways, yes, it runs now just fine. Thanks for fixing so quickly!

**Comment by khabbazian** [comment]
Great! It is possible that I have a different version installed. Thanks for letting me know. 
I will go ahead and close the issue.
