### ISSUE TITLE
Installation of l1ou

### ISSUE THREAD

**Issue by ghost** [khabbazian/l1ou#33]
Hi, I have problem in installing l10u. I'm window user, please help me in using this package. 
Thank you!

**Comment by ghost** [comment]
is this package not available for R version 3.3.3?
Warning in install.packages :
  package ‘https://github.com/khabbazian/l1ou’ is not available (for R version 3.3.3)
got this warning.

**Comment by khabbazian** [comment]
Hi Uzma,
Did you follow the instruction in the Readme file?

**Comment by ghost** [comment]
Hi Mohammad,
yes I followed the instruction, package devtools has been installed but l1ou didn't install...give this error:
> install_github("khabbazian/l1ou")
Error: could not find function "install_github"
> 
Here Rtools mention, should I first install Rtools then go for l10u?

**Comment by ghost** [comment]
infact when I downloaded Rtools then install I got this error:
> install.packages("C:/Users/Uzma/Downloads/Rtools33.exe", repos = NULL)
Installing package into ‘C:/Users/Uzma/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Error in install.packages : type == "both" cannot be used with 'repos = NULL'
>

**Comment by khabbazian** [comment]
Yes. You should install Rtools first. I am not that much familiar with Windowns. But I search your error and I find this page 
https://stackoverflow.com/questions/30123786/error-in-install-packages-type-both-cannot-be-used-with-repos-null

**Comment by ghost** [comment]
Yes I tried but it didn't work. That would be fine Mohammad, I know no one would help me in this. 
Thank you!

**Comment by khabbazian** [comment]
There is a paragraph in the Readme file about how to install the package without devtools. 
Bests

**Comment by ghost** [comment]
Yes it's been working little bit but don't know Rtools didn't download. 
> require(devtools)
Loading required package: devtools
> install_github("khabbazian/l1ou")
Downloading GitHub repo khabbazian/l1ou@master
from URL https://api.github.com/repos/khabbazian/l1ou/zipball/master
trying URL 'https://cran.rstudio.com/bin/windows/Rtools/Rtools34.exe'
Content type 'application/x-msdos-program' length 108085090 bytes (103.1 MB)
downloaded 103.1 MB

WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 3.4 from http://cran.r-project.org/bin/windows/Rtools/.
Installation failed: Could not find build tools necessary to build l1ou
>
