### ISSUE TITLE
3.4.2 compilation error

### ISSUE THREAD

**Issue by willgearty** [khabbazian/l1ou#34]
Hi,

I'm having trouble installing this package in R version 3.4.2. I've tried both methods in the readme, but both result in compilation failures.
I'd love to be able to use this software, so let me know what other information you need from me!

Best,
Will

**Comment by willgearty** [comment]
Bump @khabbazian

**Comment by cecileane** [comment]
Hi Will, could you please describe a bit more about your environment, and the error that you get? I just installed the package with no error, on a Mac (OS X 10.13.3), using `devtools` for the installation (first method). The installation instructions are actually missing a step (the middle step below), for this first method: 

```r
install.packages("devtools")
library(devtools)
install_github("khabbazian/l1ou")
```

anyway, doing `sessionInfo()` within R gave this, for me:
```
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] l1ou_1.41       genlasso_1.3    Matrix_1.2-12   MASS_7.3-49     magic_1.5-8     abind_1.4-5    
 [7] grplasso_0.4-5  lars_1.2        phylolm_2.5     ape_5.0         igraph_1.2.1    devtools_1.13.5

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16    lattice_0.20-35 digest_0.6.15   withr_2.1.2     grid_3.4.4      R6_2.2.2       
 [7] nlme_3.1-131.1  git2r_0.21.0    magrittr_1.5    httr_1.3.1      curl_3.1        tools_3.4.4    
[13] compiler_3.4.4  pkgconfig_2.0.1 memoise_1.1.0  
```

It would really help to know what kind of error you are getting, and on what kind of machine / environment.

**Comment by willgearty** [comment]
Hi and thanks for replying!
Sorry that my initial bug report was so vague. After getting your message, I decided to try uninstalling and reinstalling RTools and the associated software. After that, l1ou seems to install just fine!

**Comment by cecileane** [comment]
great to hear. thanks!
