### ISSUE TITLE
manual unavailable

### ISSUE THREAD

**Issue by cecileane** [khabbazian/l1ou#37]
There is a broken link to the manual from the readme file: [l1ou Reference manual](http://www.columbia.edu/~mhk2154/pdfs/l1ou.pdf). Could this manual be posted some other place? (just passing on user request received via email)

**Comment by cecileane** [comment]
When I try to install ℓ1ou from scratch, I get an unrelated error:

    package ‘genlasso’ is not available (for R version 3.5.1)

and indeed, checking on [CRAN](https://cran.r-project.org/web/packages/genlasso/index.html), the package has been removed from it: "Archived on 2018-06-29 as check problems were not corrected despite reminders.". What worked for me what to do this:

`install_github("khabbazian/l1ou")`

to install the dependencies of "genlasso", even if the process ends in an error because "genlasso" cannot be installed.

`install.packages("https://cran.r-project.org/src/contrib/Archive/genlasso/genlasso_1.3.tar.gz", repos = NULL, type="source")`

to install "genlasso". Doing this first failed, because at least one dependency was not found (from source code). Finally:

`install_github("khabbazian/l1ou")`

It worked after genlasso was installed (from the CRAN archive). I am on a Mac, using R v3.5.1

**Comment by khabbazian** [comment]
Apparently, genlasso is not available on CRAN anymore and should be
installed manually.

**Comment by khabbazian** [comment]
Added the manual to the package. Not the best place to have but I guess that is the best place for now.
Also updated the README file with the new instructions to install genlasso. 
Thanks
