### ISSUE TITLE
Error: object 'elist.min' not found when estimating convergent regimes using "pBIC" and  "pBICess"

### ISSUE THREAD

**Issue by Gonzobilbao** [khabbazian/l1ou#39]
Hi,

I am running the following piece of code

```
lasso1TreeB1_pBIC<-estimate_shift_configuration(AdjTree, Y[,1], criterion="pBIC")
lasso2TreeB1_pBIC <- estimate_convergent_regimes(lasso1TreeB1_pBIC, criterion="pBIC")

```
I get the following error

`Error: object 'elist.min' not found
`

This seems to be also the case when I choose the criterion "pBICess" for estimating shifts. Is there any problem with my code?

Also, this is probably a silly question, but is the criterion for estimating shifts and convergence supposed to be the same? Or can it be, say pBIC for estimating shifts and BIC/AICc/ for estimating convergence (I illustrate it with an example bellow):

```
lasso1TreeB1_pBIC<-estimate_shift_configuration(AdjTree, Y[,1], criterion="pBIC")
lasso2TreeB1_pBIC <- estimate_convergent_regimes(lasso1TreeB1_pBIC, criterion="AICc")
```

Does this make any sense? Thank you!

Gonzalo

**Comment by khabbazian** [comment]
Hi Gonzalo,
Sorry for the delay. 
The code seems correct. I guess the method only finds one shift (or maybe no shifts). Then when you run estimate_convergent_regimes you get the error.  Please let me know if that's the case.

**Comment by Gonzobilbao** [comment]
Hi Mohammed, thanks for the answer. Yes, so no shifts were found by estimate_shift_configuration, that was why the  error popped up. While doing this, I realized that the function summary.l1ou is not there, although it is on the manual. Maybe an issue with the manual installation?

Gonzalo
