### ISSUE TITLE
Error in starting.value$alpha : $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by Gonzobilbao** [khabbazian/l1ou#43]
Hi,

I get an error when estimating the convergent regimes with a tree. The function estimate_shift_configuration seems to work out fine (I get a tree with the regimes on it)
```
>AdjData<-adjust_data(MyTree, MyDataSet)

>lasso1Tree<-estimate_shift_configuration(AdjData$tree, MyDataSet[,5:6], criterion="pBIC", lars.alg = "lasso")
>lasso1Tree$nShifts
[1] 3
lasso2Tree<- estimate_convergent_regimes(lasso1Tree, criterion="pBIC")
Error in starting.value$alpha : $ operator is invalid for atomic vectors
```

Not sure what is not working. Seems like there are indeed regimes found with my tree and data set but for some reason the model produced does not seem to work when analyzing for convergence. I tried tweaking the options offered by estimate_convergent_regimes but method needs to be = "backward" since there is more than one trait, and changing fixed.alpha from TRUE to FALSE doesn't change the error message. Any pointers to what could be happening? 

Thank you very much!

**Comment by khabbazian** [comment]
close it for not having enough info to reproduce the err and fix it.
