### ISSUE TITLE
Fit Brownian motion

### ISSUE THREAD

**Issue by oscarIM** [khabbazian/l1ou#45]
Hello, I am writing to ask if it is possible to fit a Brownian model? I have tried setting the value of alpha.upper to 0 or a small value (eg. 0.001), as well as the parameters alpha.lower and alpha.starting. However, for any combination of these parameters, the program gives me the following error:

Error: $ operator is invalid for atomic vectors
Error in fit_OU_model(tree, Y, shift.configuration, opt) : 
  model score is NA in fit_OU_model function! 
		 This should not happen. Please set quietly to false to see the reason.
Also: Warning message:
In my_phylolm_interface(tr, y, s.c, opt) :
  phylolm returned error with a shift configuration
                            of size 0. You may
                            want to change alpha.upper/alpha.lower!

Greetings

**Comment by cecileane** [comment]
No, the BM is not an option in this package.
Unfortunately, I am completely swamped with other projects to make any progress on this package, and @khabbazian has moved on...

**Comment by cecileane** [comment]
[PhylogeneticEM](https://github.com/pbastide/PhylogeneticEM) has the option to use the BM, and shifts in the trait itself (instead of shifts in the optimal value).

**Comment by oscarIM** [comment]
Thank you very much Cécile for your prompt reply
Best,
