### ISSUE TITLE
matrix class warning

### ISSUE THREAD

**Issue by miltontan** [khabbazian/l1ou#46]
Hi,

I assume this is relatively minor, but I am receiving the following warning message when I run functions that detect the class of input data:

Warning message:
In if (class(Y) != "matrix") { :
  the condition has length > 1 and only the first element will be used

I believe this is related to how R v4 now has the class of matrices as a vector including "matrix" and "array".

**Comment by jakeberv** [comment]
@miltontan  Hey Milton! I'm getting this same error on 4.1.1, running osx mojave. Was this ultimately a problem for you?

**Comment by cecileane** [comment]
I suspect this was fixed by #51 (see also #50)
