### ISSUE TITLE
Error message in adjust_tree()

### ISSUE THREAD

**Issue by eliotmiller** [khabbazian/l1ou#9]
Should line 49 of the function read?
`Y <- Y[order(order(tree$tip.label)), ]`

**Comment by khabbazian** [comment]
We have that in line 73. I am not sure if I understand the problem.
Could you send me the error you get?
Thank you

**Comment by eliotmiller** [comment]
The error is "Error in order(tr$tip.label) : object 'tr' not found"

The offending line appears to be 49, which currently reads:
`Y <- Y[order(order(tr$tip.label)), ]`

If changed to the suggestion I offered above then it runs "successfully." Meaning the function doesn't return any error messages, not necessarily that it does what is intended. It appeared to work on my end.

**Comment by khabbazian** [comment]
Yes, It should have been  Y <- Y[order(order(tree$tip.label)), ]. I fixed it.
Apparently your data doesn't pass  identical(rownames(Y), tree$tip.label) condition. That means the rownames of the trait matrix doesn't match the order of the tip.label. The function reorders the rows of the matrix so that it matches the tree tip labels. 
Thank you for mentioning that.

**Comment by cecileane** [comment]
In tools.R lines 73-74, I suggest that you remove what's on line 73 (whose action is erased by line 74), and that you remove the second `order()` in line 74, which just messes things up. So it's about replacing this:

```
Y  <-  Y[order(rownames(Y)),  ] 
Y  <-  Y[order(order(tree$tip.label)), ]
```

by that:

```
Y  <-  Y[order(tree$tip.label), ]
```

As an example to illustrate why `order()` needs to be applied just once:

```
> set.seed(1)
> n = sample(letters[1:5])
> n
[1] "b" "e" "d" "c" "a"
> order(n)
[1] 5 1 4 3 2
> n[order(n)]
[1] "a" "b" "c" "d" "e"
> order(order(n))
[1] 2 5 4 3 1
> n[order(order(n))]
[1] "e" "a" "c" "d" "b"
```

**Comment by khabbazian** [comment]
Here I am trying to reorder Y rows so that the row names order matches the tree$tip.labels order. If I do what you are suggesting it just sort them alphabetically.

**Comment by khabbazian** [comment]
``` R
set.seed(1)
Y <- 1:5
names(Y) <- sample(letters[1:5])
tips <- sample(letters[1:5])
Y <- Y[order(names(Y))]
Y <- Y[order(order(tips))]
```

**Comment by cecileane** [comment]
Yes, duh, you are correct. Sorry for my mistake. There is still a much simpler option, both for the computer and for the human reading the code: replace lines 73-74 by this:

```
Y  <-  Y[tree$tip.label,  ]
```

As an example building on yours:

```
> set.seed(1)
> Y <- 1:5
> names(Y) <- sample(letters[1:5])
> tips <- sample(letters[1:5])
> Y
b e d c a 
1 2 3 4 5 
> tips
[1] "e" "d" "b" "c" "a"
> Y[tips]
e d b c a 
2 3 1 4 5 
```

**Comment by eliotmiller** [comment]
This is a related enough issue that maybe it can be included here. When the trait matrix is not in the same order as the tree, the entire matrix must be passed to the function or it returns as error. In other words, one cannot pull out a vector of trait data and pass it to the adjust_data function unless that trait vector is already sorted in the right order. Example:

```
library(geiger)
library(l1ou)

testTree <- sim.bdtree(stop="taxa", n=50)

testData <- matrix(ncol=2, nrow=50, sample(rnorm(n=100)))

rownames(testData) <- testTree$tip.label

colnames(testData) <- c("one","two")

testData <- testData[sample(row.names(testData)),]

#works
temp <- adjust_data(tree=testTree, Y=testData[,1:2])

#does not work
temp <- adjust_data(tree=testTree, Y=testData[,1])
```

**Comment by khabbazian** [comment]
Thank you Cecile. I didn't know that :) 
I replaced it with the simpler option.

**Comment by khabbazian** [comment]
Eliot,
Yes. there was some problem. After 

``` R
Y <- Y[order(names(Y)), ]
```

R changes the class from matrix to numeric when Y is a vector. That was why we got that error. 
I fixed it.
Thank you
